NumPy - Numerical Python

Advantages of NumPy Arrays:
1. Allows several mathematical operations
2. Faster operations

In [ ]:
import numpy as np

List VS NumPy arrays - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0012045890000003112


Time taken by a NumPy array

In [ ]:
numpy_array = np.array([i for i in range(10000)])

start_time = process_time()

numpy_array += 5 # such operation is not valid in list

end_time = process_time()

print(end_time - start_time)

0.00018184099999984937


NumPy Arrays

In [ ]:
# list
list1 = [1, 2, 3, 4, 5]
print(list1) # comma separated values
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array) # not separated by comma
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1-D array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# shape will give no. of rows and columns in a numpy array
a.shape

(3,)

In [ ]:
# creating a 2-D array
b = np.array([(1, 2, 3),(4, 5, 6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape

(2, 3)

In [ ]:
# creating a float 2-D array by defining its data type
c = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# creating a float numpy array
d = np.array([1.2, 3, 4, 5.666])
print(d)

[1.2   3.    4.    5.666]


Initial Placeholders in NumPy arrays

In [ ]:
# numpy array of 0s
x = np.zeros((4, 5)) # (4, 5) is the shape of array
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# numpy array of 1s
y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# numpy array of a particular value
z = np.full((3, 4), 5) # 5 is the element I want in the array
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# numpy array of identity matrix
a = np.eye(4) # as identity matrix is always square, rows and columns are equal. so, 4 is a 4 * 4 matrix.
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# numpy array of random values
b = np.random.random((2, 3)) # gives random floats between 0 and 1
print(b)

[[0.18954549 0.9762464  0.6319438 ]
 [0.13756884 0.41134538 0.67921422]]


In [ ]:
# numpy array of random integer values in a specific range
c = np.random.randint(10, 100, (3, 4)) # 10 to 100(exclusive) is range of int while (3, 4) is shape of matrix
print(c)

[[25 39 47 16]
 [23 13 44 22]
 [67 11 70 69]]


In [ ]:
# numpy array of evenly spaced values --> No. of required values
d = np.linspace(10, 40, 5) # start, stop(inclusive) and no. of values
print(d)

[10.  17.5 25.  32.5 40. ]


In [ ]:
# numpy array of evenly spaced values --> Step size in values
e = np.arange(10, 40, 5) # start, stop(exclusive) and step size
print(e)

[10 15 20 25 30 35]


In [ ]:
# convert a list to a numpy array. (same with tuple)
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10, 100, (5, 5))
print(c)

[[18 89 69 81 55]
 [81 58 88 83 26]
 [53 40 43 14 48]
 [39 32 17 47 54]
 [92 46 72 56 91]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# no. of dimension
print(c.ndim)

2


In [ ]:
# no. of elements
print(c.size)

25


In [ ]:
# data type of array elements
print(c.dtype)

int64


Mathematical operations on a numpy array

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
print(list1 + list2) # concatenates the lists rather than adding elements in lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# arithmetic operations
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))
print(a)
print(b)
print('sum: ')
print(a + b) # adds the elements in arrays instead of concatenate as in lists
print('diff: ')
print(a - b)
print('product: ')
print(a * b)
print('division:')
print(a / b)
# also supports other arithmetic operators like //, %, **

[[2 8 1]
 [2 3 9]
 [6 0 6]]
[[17 15 18]
 [15 18 17]
 [11 18 12]]
sum: 
[[19 23 19]
 [17 21 26]
 [17 18 18]]
diff: 
[[-15  -7 -17]
 [-13 -15  -8]
 [ -5 -18  -6]]
product: 
[[ 34 120  18]
 [ 30  54 153]
 [ 66   0  72]]
division:
[[0.11764706 0.53333333 0.05555556]
 [0.13333333 0.16666667 0.52941176]
 [0.54545455 0.         0.5       ]]


In [ ]:
# aggregate operations
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))
print(a)
print(b)
print('sum: ')
print(np.add(a, b)) # adds the elements in arrays instead of concatenate as in lists
print('diff: ')
print(np.subtract(a, b))
print('product: ')
print(np.multiply(a, b))
print('division:')
print(np.divide(a, b))
# also supports other aggregate operators like .mean(), .std(), .var(), .min(), .max()
# also supports operations like comparison, linera algebra, trigonometric, exponential, logarithmic

[[9 5 5]
 [6 5 5]
 [8 3 6]]
[[11 15 17]
 [16 14 18]
 [13 19 19]]
sum: 
[[20 20 22]
 [22 19 23]
 [21 22 25]]
diff: 
[[ -2 -10 -12]
 [-10  -9 -13]
 [ -5 -16 -13]]
product: 
[[ 99  75  85]
 [ 96  70  90]
 [104  57 114]]
division:
[[0.81818182 0.33333333 0.29411765]
 [0.375      0.35714286 0.27777778]
 [0.61538462 0.15789474 0.31578947]]


Array manipulation

In [49]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[1 3 0]
 [1 8 3]]
(2, 3)


In [50]:
# linear algebra
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 1]
 [3 8]
 [0 3]]
(3, 2)


In [51]:
# transpose
trans = array.T
print(trans)
print(trans.shape)

[[1 1]
 [3 8]
 [0 3]]
(3, 2)


In [59]:
# reshaping an array
reshaped_arr = array.reshape(3, 2) # same as transpose but preserves the order of elements
print(reshaped_arr)


[[1 3]
 [0 1]
 [8 3]]
