In [1]:
import numpy as np

Creating a Matrix

In [3]:
matrix1 = np.array([[1, 2], [3, 4]])
print(matrix1)

[[1 2]
 [3 4]]


In [4]:
matrix1.shape

(2, 2)

In [5]:
matrix2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
matrix2.shape

(3, 3)

Creating a matrix with random values

In [9]:
# random float matrix (always between 0 and 1)
random_float_matrix = np.random.rand(3, 3)
print(random_float_matrix)

[[0.93687022 0.97185451 0.70175127]
 [0.30347876 0.09862368 0.05028936]
 [0.58841944 0.23689126 0.45406959]]


In [11]:
# random integer matrix (between any two integers)
random_integer_matrix = np.random.randint(5, 100, size = (4, 3))
print(random_integer_matrix)

[[10 82 33]
 [ 5 38 49]
 [46 92 19]
 [39 37 15]]


Matrix with all the values as 1

In [14]:
# float
one_matrix_float = np.ones((2, 3))
print(one_matrix_float)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# integer
one_matrix_integer = np.ones((2, 3), dtype = int)
print(one_matrix_integer)

[[1 1 1]
 [1 1 1]]


Null matrix or Zero Matrix

In [16]:
# float
zero_matrix_float = np.zeros((3, 2))
print(zero_matrix_float)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
# integer
zero_matrix_integer = np.zeros((3, 2), dtype = int)
print(zero_matrix_integer)

[[0 0]
 [0 0]
 [0 0]]


Identity Matrix (always a square)

only single set of parantheses for identity matrix

In [21]:
# float
identity_matrix_float = np.eye(3, 3)
print(identity_matrix_float)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# integer
identity_matrix_integer = np.eye(3, 3, dtype = int)
print(identity_matrix_integer)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Transpose of Matrix

In [24]:
matrix = np.array([[2, 3, 4], [5, 6, 7]])
print(matrix)

transpose_matrix = np.transpose(matrix)
print(transpose_matrix)

[[2 3 4]
 [5 6 7]]
[[2 5]
 [3 6]
 [4 7]]
