In [1]:
import numpy as np

Matrix Addition (Shape of Matrices should be same)

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [7]:
print(A.shape, B.shape)

(2, 2) (2, 2)


In [8]:
sum = A + B
print(sum)

[[ 6  8]
 [10 12]]


OR

In [9]:
sum = np.add(A, B)
print(sum)

[[ 6  8]
 [10 12]]


Matrix Subtraction (Shape of Matrices should be same)

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [11]:
diff = A - B
print(diff)

[[-4 -4]
 [-4 -4]]


OR

In [12]:
diff = np.subtract(A, B)
print(diff)

[[-4 -4]
 [-4 -4]]


Multiplying a Matrix by a Scalar

In [15]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [16]:
scalar_multiply = 5 * A
print(scalar_multiply)

[[ 5 10]
 [15 20]]


OR

In [24]:
scalar_multiply = np.multiply(5, A) # np.product is for scalar
print(scalar_multiply)

[[ 5 10]
 [15 20]
 [10 15]]


Multiplying 2 Matrices

- the shape Required for matrix multiplication is **(a, b)** and **(b, c)** where the Resultant Matrix will be **(a, c)**

In [19]:
A = np.array([[1, 2], [3, 4], [2, 3]])
B = np.array([[5, 6], [7, 8]])
print(A.shape, B.shape)

(3, 2) (2, 2)


In [20]:
print(A)

[[1 2]
 [3 4]
 [2 3]]


In [21]:
print(B)

[[5 6]
 [7 8]]


In [29]:
# np.dot: A versatile function that performs different operations based on input dimensions.
# 1D arrays (Vectors): Computes the dot product.
# 2D arrays (Matrices): Performs matrix multiplication.

# or you can use A @ B for matrix multiplication
matrix_product = np.dot(A, B)
print(matrix_product)

[[19 22]
 [43 50]
 [31 36]]


In [27]:
matrix_product.shape

(3, 2)

Element wisw Matrix Multiplication (Requires same shape of matrices)

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A.shape, B.shape)

(2, 2) (2, 2)


In [35]:
print(A)

[[1 2]
 [3 4]]


In [36]:
print(B)

[[5 6]
 [7 8]]


In [37]:
element_matrix_multiplication = np.multiply(A, B)
print(element_matrix_multiplication)

[[ 5 12]
 [21 32]]
